{
	"items" :      [
		{
			"interests" :     "UI Integration,Process Space Management Systems,Processes and services,Improving the knowledge creation and evaluation process",
			"country" :       "Italy",
			"affilation" :    "University of Trento",
			"lab" :           "HP",
			"origin-field" :  "workflow",
			"email" :         "fabio.casati(at)dit.unitn.it",
			"detaildescurl" : "./Experts/Fabio.html",
			"type" :          "Item",
			"label" :         "Fabio Casati",
			"imageurl" :      "http://dit.unitn.it/img/photos/casati.jpg",
			"homepage" :      "http://dit.unitn.it/~casati"
		},
		{
			"interests" :     "Information Systems,Workflow,Petri Net,Process Mining",
			"enterdate" :     1992,
			"teamUrl" :       "http://www.win.tue.nl/ais/doku.php",
			"country" :       "Netherlands",
			"affilation" :    "Eindhoven University of Technology(TU/e)",
			"lab" :           "AIS at TU/e",
			"briefdesc" :     "director of Architecture of Information Systems (AIS) group, TU/e",
			"origin-field" :  "workflow",
			"email" :         "w.m.p.v.d.aalst(at)tue.nl",
			"type" :          "Item",
			"detaildescurl" : "./Experts/wmp.html",
			"label" :         "W.M.P van der Aalst",
			"imageurl" :      "http://is.tm.tue.nl/staff/wvdaalst/photo_wil_small_small.JPG",
			"homepage" :      "http://is.tm.tue.nl/staff/wvdaalst/"
		},
		{
			"interests" :     "Web service protocols analysis and management, enterprise services integration, large scale and autonomous data sharing, process modeling and service oriented architectures for pervasive computing",
			"teamUrl" :       "http://soc.web.cse.unsw.edu.au/index.php",
			"country" :       "Australia",
			"affilation" :    "University of New South Wales Sydney, Australia",
			"lab" :           "SOC at UNSW",
			"briefdesc" :     "leader of the Service Oriented Computing (SOC) research group at CSE, UNSW",
			"origin-field" :  "db & workflow",
			"email" :         "boualem(at)cse.unsw.edu.au",
			"type" :          "Item",
			"detaildescurl" : "./Experts/Boualem.html",
			"label" :         "Boualem Benatallah",
			"imageurl" :      "http://www.cse.unsw.edu.au/db/staff/Images/boualem.jpg",
			"homepage" :      "http://www.cse.unsw.edu.au/~boualem/"
		},
		{
			"interests" :     "Semantic Web and Knowledge Discovery,Workflow Management and Web Services",
			"enterdate" :     1998,
			"teamUrl" :       "http://lsdis.cs.uga.edu/",
			"country" :       "USA",
			"affilation" :    "University of Georgia",
			"lab" :           "LSDIS at UGA",
			"origin-field" :  "db & workflow",
			"email" :         "budak(at)cs.uga.edu",
			"type" :          "Item",
			"detaildescurl" : "./Experts/Ibudak.html",
			"label" :         "I. Budak Arpinar",
			"imageurl" :      "http://webster.cs.uga.edu/%7Ebudak/ben23.jpg",
			"homepage" :      "http://www.cs.uga.edu/~budak"
		},
		{
			"interests" :     "SOC",
			"teamUrl" :       "http://domino.research.ibm.com/comm/research.nsf/pages/r.servcomp.html",
			"country" :       "USA",
			"affilation" :    "IBM T.J. Watson Research Center",
			"briefdesc" :     "graduated ph.d student in SOC Group, UNSW",
			"lab" :           "IBM WRC",
			"detaildescurl" : "./Experts/liangzhaozeng.html",
			"type" :          "Item",
			"label" :         "liangzhao Zeng"
		},
		{
			"interests" :     "Web service platform",
			"teamUrl" :       "http://domino.research.ibm.com/comm/research.nsf/pages/r.servcomp.html",
			"country" :       "USA",
			"affilation" :    "WSO2",
			"lab" :           "IBM WRC",
			"briefdesc" :     "one of the founders of the IBM Web services platform",
			"origin-field" :  "PSE(Problem Solving Environment)",
			"email" :         "sanjiva(at)wso2.com",
			"type" :          "Item",
			"detaildescurl" : "./Experts/sanjiva.html",
			"label" :         "Sanjiva Weerawarana",
			"imageurl" :      "http://wso2.com/wp-content/themes/wso2ng/images/sanjiva.gif",
			"homepage" :      "http://www.bloglines.com/blog/sanjiva"
		},
		{
			"interests" :     "Semantic Web and Semantic Applications, Digital Library, Web and Business Process,etc.",
			"teamUrl" :       "http://lsdis.cs.uga.edu/",
			"country" :       "USA",
			"affilation" :    "University of Georgia",
			"lab" :           "LSDIS at UGA",
			"briefdesc" :     "director of the Large Scale Distributed Information Systems (LSDIS) Lab, at the University of Georgia.",
			"origin-field" :  "db & workflow",
			"email" :         "amit(at)cs.uga.edu",
			"type" :          "Item",
			"detaildescurl" : "./Experts/amit.html",
			"label" :         "Amit Sheth",
			"imageurl" :      "http://knoesis.wright.edu/pictures/CK_6497.jpg",
			"homepage" :      "http://lsdis.cs.uga.edu/~amit/"
		},
		{
			"interests" :    "SOC",
			"teamUrl" :      "http://domino.research.ibm.com/comm/research.nsf/pages/r.servcomp.html",
			"country" :      "USA",
			"affilation" :   "IBM T.J. Watson Research Center",
			"lab" :          "IBM WRC",
			"briefdesc" :    "co-author of the BPEL4WS, WSDL and WSFL specifications, and co-developer of BPWS4J, Apache SOAP and WSTK",
			"origin-field" : "SOC",
			"email" :        "curbera(at)us.ibm.com",
			"type" :         "Item",
			"label" :        "Francisco Curbera",
			"imageurl" :     "http://is.tm.tue.nl/bpm2003/images/curbera%5B1%5D.jpg"
		},
		{
			"interests" :     "SOC",
			"enterdate" :     1996,
			"teamUrl" :       "http://domino.research.ibm.com/comm/research.nsf/pages/r.servcomp.html",
			"country" :       "USA",
			"affilation" :    "IBM T.J. Watson Research Center",
			"lab" :           "IBM WRC",
			"origin-field" :  "Networked Multimedia",
			"type" :          "Item",
			"detaildescurl" : "./Experts/LJZhang.html",
			"label" :         "Liang-Jie Zhang",
			"imageurl" :      "http://domino.research.ibm.com/comm/research_people.nsf/pages/zhanglj8.index.html/$FILE/824462897.jpg",
			"homepage" :      "http://domino.research.ibm.com/comm/research_people.nsf/pages/zhanglj8.index.html"
		},
		{
			"interests" :    "Web Services Community and data integration",
			"teamUrl" :      "http://soc.web.cse.unsw.edu.au/index.php",
			"country" :      "Australia",
			"affilation" :   "University of New South Wales Sydney, Australia",
			"lab" :          "SOC at UNSW",
			"origin-field" : "SOC",
			"email" :        "hpaik(at)cse.unsw.edu.au",
			"type" :         "Item",
			"label" :        "Hye-young Helen Paik",
			"imageurl" :     "http://www.cse.unsw.edu.au/~hpaik/me.jpg",
			"homepage" :     "http://www.cse.unsw.edu.au/~hpaik/"
		},
		{
			"interests" :     "Many areas of information technology, including service-oriented computing, distributed artificial intelligence and multiagent systems, machine learning, computer vision, enterprise integration, and computational social systems",
			"teamUrl" :       "http://www.cse.sc.edu/research/cit",
			"country" :       "USA",
			"affilation" :    "University of South Carolina",
			"lab" :           "Center for Information Technology,USC",
			"briefdesc" :     "Director of the Center for Information Technology",
			"origin-field" :  "AI",
			"email" :         "huhns(at)sc.edu",
			"type" :          "Item",
			"detaildescurl" : "./Experts/huhns.html",
			"label" :         "Michael N. Huhns",
			"imageurl" :      "http://www.cse.sc.edu/~huhns/gifs/Huhns25November06.jpg",
			"homepage" :      "http://www.cse.sc.edu/~huhns/"
		},
		{
			"enterdate" :     1994,
			"teamUrl" :       "http://www.iaas.uni-stuttgart.de/indexE.html",
			"country" :       "Jermany",
			"affilation" :    "University of Stuttgart",
			"lab" :           "IAAS",
			"briefdesc" :     "father of IBM workflow product set",
			"origin-field" :  "db & workflow",
			"email" :         "Leymann(at)iaas.uni-stuttgart.de",
			"type" :          "Item",
			"detaildescurl" : "./Experts/FrankBio.html",
			"label" :         "Prof. Dr. Frank Leymann",
			"imageurl" :      "http://www.iaas.uni-stuttgart.de/institut/mitarbeiter/images/fleymann2.jpg",
			"homepage" :      "http://www.iaas.uni-stuttgart.de/institut/mitarbeiter/leymann/indexE.php"
		},
		{
			"interests" :  "SOC,software engineering, software architecture and pattern",
			"teamUrl" :    "http://domino.research.ibm.com/comm/research.nsf/pages/r.servcomp.html",
			"country" :    "USA",
			"affilation" : "IBM Global Services",
			"lab" :        "IBM Global Services",
			"briefdesc" :  "Chief Architect of the SOA and Web Services Center of Excellence",
			"email" :      "aarsanjani AT mum.edu",
			"type" :       "Item",
			"label" :      "Ali Arsanjani",
			"imageurl" :   "https://www.mum.edu/images/inside/faculty_photo_arsanjani_ali.jpg",
			"homepage" :   "http://www.arsanjani.com/"
		},
		{
			"interests" :     "Multiagent systems,Networked applications (e-commerce, Web services, mobile computing)",
			"teamUrl" :       "http://research.csc.ncsu.edu/mas/",
			"country" :       "USA",
			"affilation" :    "North Carolina State University",
			"lab" :           "Multiagent Systems and Service-Oriented Computing Laboratory,NCSU",
			"briefdesc" :     "Director of Multiagent Systems and Service-Oriented Computing Laboratory",
			"origin-field" :  "AI",
			"email" :         "singh(at)ncsu.edu",
			"type" :          "Item",
			"detaildescurl" : "./Experts/Singh.html",
			"label" :         "Munindar P. Singh",
			"imageurl" :      "http://people.engr.ncsu.edu/mpsingh/mps/munindar-sep-04-a.jpg",
			"homepage" :      "http://people.engr.ncsu.edu/mpsingh/"
		},
		{
			"interests" :     "Service-oriented Architectures and Computing, Mobile and Ubiquitous Computing, Complex-, Autonomic-, and Adaptive Systems, and Context-aware Computing including all aspects related to collaborative systems (e.g., Workflow technologies)",
			"enterdate" :     2005,
			"teamUrl" :       "http://www.vitalab.tuwien.ac.at/",
			"country" :       "Austria",
			"affilation" :    "Information Systems Institute\nVienna University of Technology",
			"lab" :           "VITA",
			"briefdesc" :     "Head of the Distributed Systems Group\nDirector of Vita Lab",
			"origin-field" :  "workflow",
			"email" :         "dustdar@infosys.tuwien.ac.at",
			"type" :          "Item",
			"detaildescurl" : "./Experts/Schahram Dustdar.htm",
			"label" :         "Schahram Dustdar",
			"imageurl" :      "http://www.infosys.tuwien.ac.at/staff/sd/Foto.JPG",
			"homepage" :      "http://www.infosys.tuwien.ac.at/staff/sd/"
		},
		{
			"interests" :     "AI and the Web",
			"teamUrl" :       "http://lsdis.cs.uga.edu/",
			"country" :       "USA",
			"affilation" :    "University of Georgia",
			"lab" :           "LSDIS at UGA",
			"origin-field" :  "AI",
			"email" :         "pdoshi AT cs DOT uga DOT edu",
			"type" :          "Item",
			"detaildescurl" : "./Experts/doshi.html",
			"label" :         "Prashant Doshi",
			"imageurl" :      "http://www.cs.uga.edu/~pdoshi/doshi.jpg",
			"homepage" :      "http://www.cs.uga.edu/~pdoshi/"
		},
		{
			"interests" :     "Cooperative Database/Information Systems,WWW Information Discovery and Retrieval Techniques,Information Brokering and E-Business,SOC",
			"enterdate" :     1997,
			"teamUrl" :       "http://infolab.uvt.nl/",
			"country" :       "Netherlands",
			"affilation" :    "Tilburg University, The Netherlands",
			"lab" :           "InfoLab at Tilburg University",
			"origin-field" :  "db & information systems",
			"email" :         "mikep(at)uvt.nl",
			"type" :          "Item",
			"detaildescurl" : "./Experts/Mike.html",
			"label" :         "Mike P. Papazoglou",
			"imageurl" :      "http://infolab.uvt.nl/~mikep/mike-small.jpg",
			"homepage" :      "http://infolab.uvt.nl/~mikep/"
		}
	],
	"properties" : {
		"enterdate" : {
			"valueType" : "number"
		}
	}
}